// Module 1a: parse a PrusaSlicer/SuperSlicer .ini into a neutral structure.
//
// Two shapes exist in the wild:
//   - "Export Config"        -> a flat key=value file (no section headers)
//   - "Export Config Bundle" -> sections like [filament:NAME], [printer:NAME], [presets]
//
// Values can be quoted ("...") and may span... no: PrusaSlicer keeps each setting on
// one physical line, encoding newlines inside custom g-code as the literal "\n".

export interface ParsedIni {
  /** Header comment, e.g. "generated by PrusaSlicer 2.9.5 on ..." */
  header?: string;
  /** Present when the file is a flat single-config export. */
  flat?: Record<string, string>;
  /** Present when the file is a bundle: section name -> key/value map. */
  sections?: Map<string, Record<string, string>>;
}

const SECTION_RE = /^\[(.+)\]\s*$/;

export function parseIni(text: string): ParsedIni {
  const lines = text.split(/\r?\n/);
  let header: string | undefined;
  const flat: Record<string, string> = {};
  const sections = new Map<string, Record<string, string>>();
  let current: Record<string, string> | null = null;
  let sawSection = false;

  for (const raw of lines) {
    const line = raw.trimEnd();
    if (line.length === 0) continue;
    if (line.startsWith("#") || line.startsWith(";")) {
      if (!header) header = line.replace(/^[#;]\s?/, "");
      continue;
    }
    const sec = SECTION_RE.exec(line);
    if (sec) {
      sawSection = true;
      current = {};
      sections.set(sec[1]!.trim(), current);
      continue;
    }
    const eq = line.indexOf("=");
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    value = stripWrappingQuotes(value);
    if (current) current[key] = value;
    else flat[key] = value;
  }

  const result: ParsedIni = { header };
  if (sawSection) result.sections = sections;
  else result.flat = flat;
  return result;
}

/** PrusaSlicer wraps some values (notably g-code/notes) in double quotes. */
export function stripWrappingQuotes(v: string): string {
  if (v.length >= 2 && v.startsWith('"') && v.endsWith('"')) {
    return v.slice(1, -1);
  }
  return v;
}

/** Best-effort slicer + version from the header comment. */
export function detectSource(header: string | undefined, file?: string): {
  slicer: string;
  version?: string;
  file?: string;
} {
  if (!header) return { slicer: "PrusaSlicer", file };
  const slicer = /SuperSlicer/i.test(header) ? "SuperSlicer" : "PrusaSlicer";
  const m = /(\d+\.\d+(?:\.\d+)?)/.exec(header);
  return { slicer, version: m?.[1], file };
}
