#!/usr/bin/env tsx
// The "up-to-date" engine.
//
// Walks OrcaSlicer's own filament profiles on GitHub and emits the union of every
// key they use. That key set is what the engine validates output against, so the
// target schema tracks whatever OrcaSlicer release we point at instead of rotting
// on a hardcoded version (the failure mode of every existing converter).
//
// Usage:
//   tsx src/sync.ts [--ref main] [--vendor Prusa] [--limit 250]
//
// Output is written to ../engine/src/schema/orcaFilament.generated.ts and printed
// as a diff summary so a human (or CI bot) consciously reviews added/removed keys.

import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, "../../engine/src/schema/orcaFilament.generated.ts");

interface GhTreeItem { path: string; type: string }

function arg(name: string, def: string): string {
  const i = process.argv.indexOf(`--${name}`);
  return i !== -1 && process.argv[i + 1] ? process.argv[i + 1]! : def;
}

async function ghJson<T>(url: string): Promise<T> {
  const headers: Record<string, string> = { "User-Agent": "finsync-schema-sync" };
  if (process.env.GITHUB_TOKEN) headers.Authorization = `Bearer ${process.env.GITHUB_TOKEN}`;
  const res = await fetch(url, { headers });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  return (await res.json()) as T;
}

async function main(): Promise<void> {
  const ref = arg("ref", "main");
  const vendor = arg("vendor", "Prusa");
  const limit = Number(arg("limit", "250"));

  console.log(`Syncing Orca filament schema from OrcaSlicer@${ref} (vendor=${vendor})…`);

  const tree = await ghJson<{ tree: GhTreeItem[] }>(
    `https://api.github.com/repos/OrcaSlicer/OrcaSlicer/git/trees/${ref}?recursive=1`,
  );
  const files = tree.tree
    .filter((t) => t.type === "blob")
    .filter((t) => t.path.includes(`resources/profiles/${vendor}/filament/`))
    .filter((t) => t.path.endsWith(".json"))
    .slice(0, limit);

  console.log(`Scanning ${files.length} filament profiles…`);
  const keys = new Set<string>();
  let scanned = 0;
  for (const f of files) {
    const raw = await ghJson<Record<string, unknown>>(
      `https://raw.githubusercontent.com/OrcaSlicer/OrcaSlicer/${ref}/${f.path}`,
    ).catch(() => null);
    if (!raw) continue;
    for (const k of Object.keys(raw)) keys.add(k);
    if (++scanned % 25 === 0) console.log(`  …${scanned}/${files.length}`);
  }

  const sorted = [...keys].sort();
  const prev = existsSync(OUT) ? extractKeys(readFileSync(OUT, "utf8")) : new Set<string>();
  const added = sorted.filter((k) => !prev.has(k));
  const removed = [...prev].filter((k) => !keys.has(k));

  writeFileSync(OUT, render(ref, vendor, scanned, sorted));
  console.log(`\nWrote ${sorted.length} keys to ${OUT}`);
  console.log(`  + added:   ${added.length ? added.join(", ") : "(none)"}`);
  console.log(`  - removed: ${removed.length ? removed.join(", ") : "(none)"}`);
  if (added.length || removed.length) {
    console.log("\n⚠ Review these schema changes before shipping — new keys may need mapping entries.");
  }
}

function extractKeys(src: string): Set<string> {
  const m = src.match(/"([^"]+)"/g) ?? [];
  return new Set(m.map((s) => s.slice(1, -1)));
}

function render(ref: string, vendor: string, count: number, keys: string[]): string {
  return `// AUTO-GENERATED by @finsync/schema-sync — do not edit by hand.
// Source: OrcaSlicer@${ref} resources/profiles/${vendor}/filament (${count} profiles scanned).
export const ORCA_FILAMENT_KEYS_GENERATED: ReadonlySet<string> = new Set([
${keys.map((k) => `  ${JSON.stringify(k)},`).join("\n")}
]);
`;
}

main().catch((e) => {
  console.error("schema-sync failed:", e.message);
  process.exit(1);
});
