import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import {
  convertIniToOrcaFilaments,
  extractFilamentProfiles,
} from "../src/index.js";
import { unbackslash } from "../src/transform/gcode.js";

const FIX = join(__dirname, "fixtures");
const read = (f: string) => readFileSync(join(FIX, f), "utf8");

describe("config bundle (real fixture: Plymaker ABS @COREONE HF0.6)", () => {
  const results = convertIniToOrcaFilaments(read("PrusaSlicer_config_bundle.ini"));
  const abs = results.find((r) => r.profile.name === "Plymaker ABS @COREONE HF0.6");

  it("extracts exactly the filament section", () => {
    expect(results).toHaveLength(1);
    expect(abs).toBeDefined();
  });

  it("emits a well-formed Orca filament header", () => {
    expect(abs!.profile.type).toBe("filament");
    expect(abs!.profile.from).toBe("User");
    expect(abs!.profile.instantiation).toBe("true");
  });

  it("wraps every setting value in a single-element string array", () => {
    expect(abs!.profile.nozzle_temperature).toEqual(["260"]);
    expect(abs!.profile.filament_type).toEqual(["ABS"]);
    expect(abs!.profile.filament_max_volumetric_speed).toEqual(["34"]);
  });

  it("fans bed_temperature out to all four Orca plate types", () => {
    for (const k of ["hot_plate_temp", "cool_plate_temp", "eng_plate_temp", "textured_plate_temp"]) {
      expect(abs!.profile[k]).toEqual(["110"]);
    }
  });

  it("renames fan/cooling keys to Orca equivalents", () => {
    expect(abs!.profile.overhang_fan_speed).toEqual(["25"]); // bridge_fan_speed
    expect(abs!.profile.close_fan_the_first_x_layers).toEqual(["4"]); // disable_fan_first_layers
    expect(abs!.profile.fan_max_speed).toEqual(["20"]); // max_fan_speed
  });

  it("skips `nil` overrides so Orca inherits them", () => {
    expect(abs!.profile.filament_retraction_length).toBeUndefined();
    expect(abs!.stats.nilSkipped).toBeGreaterThan(0);
  });

  it("auto-resolves the system parent to the real Orca preset name", () => {
    expect(abs!.inherits).toEqual({
      kind: "resolved",
      prusa: "Generic ABS @COREONE HF0.6",
      orca: "Prusa Generic ABS @CORE One HF 0.6",
    });
    expect(abs!.profile.inherits).toBe("Prusa Generic ABS @CORE One HF 0.6");
  });

  it("un-escapes custom g-code into real newlines", () => {
    const g = abs!.profile.filament_start_gcode as string[];
    expect(g[0]).toContain("\n");
    expect(g[0]).not.toContain("\\n");
  });

  it("only emits keys the current Orca schema accepts", () => {
    expect(abs!.stats.droppedInvalid).toBe(0);
  });

  it("passes through Prusa keys that are identical in current Orca (schema-driven)", () => {
    // These have no manual mapping entry but exist 1:1 in Orca's live schema.
    expect(abs!.profile.filament_cooling_moves).toEqual(["3"]);
    expect(abs!.profile.filament_ramming_parameters).toBeDefined();
  });
});

describe("flat Export Config (real fixture: config.ini)", () => {
  const results = convertIniToOrcaFilaments(read("config.ini"));

  it("pulls one filament profile out of the combined config", () => {
    expect(results).toHaveLength(1);
    expect(results[0]!.profile.name).toBe("Prusament PLA @COREONE HF0.6");
  });

  it("does not leak print/printer keys into the filament profile", () => {
    const p = results[0]!.profile;
    expect(p.layer_height).toBeUndefined();
    expect(p.bottom_shell_layers).toBeUndefined();
    expect(p.filament_type).toEqual(["PLA"]);
  });
});

describe("max_volumetric_speed = 0 substitution", () => {
  it("replaces an illegal 0 with a per-type default", () => {
    const ini = [
      "# generated by PrusaSlicer 2.9.5",
      "[filament:Test PLA]",
      "filament_type = PLA",
      "filament_max_volumetric_speed = 0",
      "temperature = 215",
    ].join("\n");
    const [r] = convertIniToOrcaFilaments(ini);
    expect(r!.profile.filament_max_volumetric_speed).toEqual(["15"]);
  });
});

describe("filament_type aliasing", () => {
  it("maps PET/FLEX/NYLON to Orca names", () => {
    const ini = "[filament:X]\nfilament_type = FLEX\ntemperature = 230\n";
    const [r] = extractFilamentProfiles(ini).map((p) => p);
    expect(r).toBeDefined();
    const out = convertIniToOrcaFilaments(ini)[0]!;
    expect(out.profile.filament_type).toEqual(["TPU"]);
  });
});

describe("printer-compatibility rules are dropped (so Orca will import)", () => {
  const ini = [
    "# generated by PrusaSlicer 2.9.5",
    "[filament:Test PLA]",
    "filament_type = PLA",
    "temperature = 215",
    "compatible_printers_condition = printer_model=~/(MK4|MK3.9)/ and nozzle_diameter[0]==0.6",
  ].join("\n");
  const [r] = convertIniToOrcaFilaments(ini);

  it("does not emit compatible_printers_condition (the import-rejection cause)", () => {
    expect(r!.profile.compatible_printers_condition).toBeUndefined();
  });

  it("flags the drop in the report", () => {
    expect(
      r!.report.some(
        (e) => e.sourceKey === "compatible_printers_condition" && e.severity === "warn",
      ),
    ).toBe(true);
  });
});

describe("unbackslash", () => {
  it("converts literal escapes to characters", () => {
    expect(unbackslash("a\\nb\\tc")).toBe("a\nb\tc");
    expect(unbackslash('say \\"hi\\"')).toBe('say "hi"');
    expect(unbackslash("trailing\\")).toBe("trailing\\");
  });
});
